### ISSUE TITLE
Error when trying to use ruff from selected virtual environment

### ISSUE THREAD

**Issue by brettcannon** [charliermarsh/vscode-ruff#17]
When trying to use my environment's copy of ruff to get 0.0.116, I get the following error:

```
Server Command [RUN]: /Users/brettcannon/Repositories/brettcannon/mousebender/.venv/bin/python /Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/tool/server.py
Server Command [DEBUG]: /Users/brettcannon/Repositories/brettcannon/mousebender/.venv/bin/python /Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/tool/_debug_server.py
Exception ignored in atexit callback: <function ProcessManager.stop_all_processes at 0x10d1260c0>
TypeError: ProcessManager.stop_all_processes() missing 1 required positional argument: 'self'
Name or version is not set. This will be mandatory: https://github.com/openlawlibrary/pygls/pull/276
CWD Server: /Users/brettcannon/Repositories/brettcannon/mousebender
sys.path used to run Server:
   /Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/tool
   /usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python311.zip
   /usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11
   /usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/lib-dynload
   /Users/brettcannon/Repositories/brettcannon/mousebender/.venv/lib/python3.11/site-packages
   /Users/brettcannon/Repositories/brettcannon/mousebender
   /Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/libs
Settings used to run Server:
[
    {
        "workspace": "file:///Users/brettcannon/Repositories/brettcannon/mousebender",
        "logLevel": "warn",
        "args": [],
        "path": [],
        "interpreter": [
            "/Users/brettcannon/Repositories/brettcannon/mousebender/.venv/bin/python"
        ],
        "importStrategy": "fromEnvironment",
        "showNotifications": "off"
    }
]

ruff --no-cache --format json - --stdin-filename /Users/brettcannon/Repositories/brettcannon/mousebender/mousebender/simple.py
CWD Server: /Users/brettcannon/Repositories/brettcannon/mousebender
Failed to handle user defined notification "textDocument/didOpen": (DidOpenTextDocumentParams(text_document=TextDocumentItem(uri='file:///Users/brettcannon/Repositories/brettcannon/mousebender/mousebender/simple.py', language_id='python', version=1, text='from __future__ import annotations\n\n# import html\nimport html.parser\nimport urllib.parse\nfrom typing import Dict, List, Union\n\nimport packaging.specifiers\nimport packaging.utils\nimport html\nimport sys\n\n# Python 3.8+ only.\nfrom typing_extensions import Literal, TypedDict\n\n\ndef create_project_url(base_url: str, project_name: str) -> str:\n    """Construct the project URL for a repository following PEP 503."""\n    if base_url and not base_url.endswith("/"):\n        base_url += "/"  # Normalize for easier use w/ str.join() later.\n    # PEP 503:\n    # The format of this URL is /<project>/ where the <project> is replaced by\n    # the normalized name for that project, so a project named "HolyGrail" would\n    # have a URL like /holygrail/.\n    #\n    # All URLs which respond with an HTML5 page MUST end with a / and the\n    # repository SHOULD redirect the URLs without a / to add a / to the end.\n    return "".join([base_url, packaging.utils.canonicalize_name(project_name), "/"])\n\n\n_Meta = TypedDict("_Meta", {"api-version": Literal["1.0"]})\n\n\nclass ProjectIndex(TypedDict):\n    meta: _Meta\n    projects: List[Dict[Literal["name"], str]]\n\n\n_HashesDict = Dict[str, str]\n_OptionalProjectFileDetails = TypedDict(\n    "_OptionalProjectFileDetails",\n    {\n        "requires-python": str,\n        "dist-info-metadata": Union[bool, _HashesDict],\n        "gpg-sig": bool,\n        "yanked": Union[bool, str],\n    },\n    total=False,\n)\n\n\nclass ProjectFileDetails(_OptionalProjectFileDetails):\n    filename: str\n    url: str\n    hashes: _HashesDict\n\n\nclass ProjectDetails(TypedDict):\n    meta: _Meta\n    name: packaging.utils.NormalizedName\n    files: list[ProjectFileDetails]\n\n\nclass _SimpleIndexHTMLParser(html.parser.HTMLParser):\n\n    """Parse the HTML of a repository index page."""\n\n    # PEP 503:\n    # Within a repository, the root URL (/) MUST be a valid HTML5 page with a\n    # single anchor element per project in the repository.\n\n    def __init__(self):\n        super().__init__()\n        self._parsing_anchor = False\n        self.names = []\n\n    def handle_starttag(self, tag, _attrs_list):\n        if tag != "a":\n            return\n        self._parsing_anchor = True\n\n    def handle_endtag(self, tag):\n        if tag != "a":\n            return\n        self._parsing_anchor = False\n\n    def handle_data(self, data):\n        if self._parsing_anchor:\n            self.names.append(data)\n\n\ndef from_project_index_html(html: str) -> ProjectIndex:\n    """Parse the HTML of a repository index page."""\n    parser = _SimpleIndexHTMLParser()\n    parser.feed(html)\n    project_index: ProjectIndex = {\n        "meta": {"api-version": "1.0"},\n        "projects": [{"name": name} for name in parser.names],\n    }\n    return project_index\n\n\nclass _ArchiveLinkHTMLParser(html.parser.HTMLParser):\n    def __init__(self):\n        self.archive_links = []\n        super().__init__()\n\n    def handle_starttag(self, tag, attrs_list):\n        attrs = dict(attrs_list)\n        if tag != "a":\n            return\n        # PEP 503:\n        # The href attribute MUST be a URL that links to the location of the\n        # file for download ...\n        full_url = attrs["href"]\n        parsed_url = urllib.parse.urlparse(full_url)\n        # PEP 503:\n        # ... the text of the anchor tag MUST match the final path component\n        # (the filename) of the URL.\n        _, _, raw_filename = parsed_url.path.rpartition("/")\n        filename = urllib.parse.unquote(raw_filename)\n        url = urllib.parse.urlunparse((*parsed_url[:5], ""))\n        args = {"filename": filename, "url": url}\n        # PEP 503:\n        # The URL SHOULD include a hash in the form of a URL fragment with the\n        # following syntax: #<hashname>=<hashvalue> ...\n        if parsed_url.fragment:\n            hash_algo, hash_value = parsed_url.fragment.split("=", 1)\n            args["hashes"] = hash_algo.lower(), hash_value\n        # PEP 503:\n        # A repository MAY include a data-requires-python attribute on a file\n        # link. This exposes the Requires-Python metadata field ...\n        # In the attribute value, < and > have to be HTML encoded as &lt; and\n        # &gt;, respectively.\n        if "data-requires-python" in attrs:\n            requires_python_data = html.unescape(attrs["data-requires-python"])\n            args["requires-python"] = requires_python_data\n        # PEP 503:\n        # A repository MAY include a data-gpg-sig attribute on a file link with\n        # a value of either true or false ...\n        if "data-gpg-sig" in attrs:\n            args["gpg-sig"] = attrs["data-gpg-sig"] == "true"\n        # PEP 592:\n        # Links in the simple repository MAY have a data-yanked attribute which\n        # may have no value, or may have an arbitrary string as a value.\n        if "data-yanked" in attrs:\n            args["yanked"] = attrs.get("data-yanked") or True\n        # PEP 658:\n        # ... each anchor tag pointing to a distribution MAY have a\n        # data-dist-info-metadata attribute.\n        if "data-dist-info-metadata" in attrs:\n            metadata = attrs.get("data-dist-info-metadata")\n            if metadata and metadata != "true":\n                # The repository SHOULD provide the hash of the Core Metadata\n                # file as the data-dist-info-metadata attribute\'s value using\n                # the syntax <hashname>=<hashvalue>, where <hashname> is the\n                # lower cased name of the hash function used, and <hashvalue> is\n                # the hex encoded digest.\n                algorithm, _, hash = metadata.partition("=")\n                metadata = (algorithm.lower(), hash)\n            else:\n                # The repository MAY use true as the attribute\'s value if a hash\n                # is unavailable.\n                metadata = "", ""\n            args["metadata"] = metadata\n\n        self.archive_links.append(args)\n\n\ndef from_project_details_html(name: str, html: str) -> ProjectDetails:\n    parser = _ArchiveLinkHTMLParser()\n    parser.feed(html)\n    files: List[ProjectFileDetails] = []\n    for archive_link in parser.archive_links:\n        details: ProjectFileDetails = {\n            "filename": archive_link["filename"],\n            "url": archive_link["url"],\n            "hashes": {},\n        }\n        if "hashes" in archive_link:\n            details["hashes"] = dict([archive_link["hashes"]])\n        if "metadata" in archive_link:\n            algorithm, value = archive_link["metadata"]\n            if algorithm:\n                details["dist-info-metadata"] = {algorithm: value}\n            else:\n                details["dist-info-metadata"] = True\n        for key in {"requires-python", "yanked", "gpg-sig"}:\n            if key in archive_link:\n                details[key] = archive_link[key]  # type: ignore\n        files.append(details)\n    return {\n        "meta": {"api-version": "1.0"},\n        "name": packaging.utils.canonicalize_name(name),\n        "files": files,\n    }\n')),)
Traceback (most recent call last):
  File "/Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/libs/pygls/protocol.py", line 77, in decorator
    self._execute_notification(user_func, *args, **kwargs)
  File "/Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/libs/pygls/protocol.py", line 223, in _execute_notification
    handler(*params)
  File "/Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/tool/server.py", line 75, in did_open
    diagnostics: list[lsp.Diagnostic] = _linting_helper(document)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/tool/server.py", line 104, in _linting_helper
    result = _run_tool_on_document(document, use_stdin=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/tool/server.py", line 316, in _run_tool_on_document
    result = utils.run_path(
             ^^^^^^^^^^^^^^^
  File "/Users/brettcannon/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-x64/bundled/tool/utils.py", line 148, in run_path
    with subprocess.Popen(
         ^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ruff'
```

To help show that I have ruff in the environment:

```
mousebender on  main [$!] via 🐍 v3.11.0 
❯ source /Users/brettcannon/Repositories/brettcannon/mousebender/.venv/bin/activate.fish

mousebender on  main [$!] via 🐍 v3.11.0 (mousebender) 
❯ ruff --version
ruff 0.0.116

mousebender on  main [$!] via 🐍 v3.11.0 (mousebender) 
❯ which ruff
/Users/brettcannon/Repositories/brettcannon/mousebender/.venv/bin/ruff
```

**Comment by charliermarsh** [comment]
Thanks! Will dig into this.

**Comment by charliermarsh** [comment]
Fixed in 2022.0.13.

**Comment by brettcannon** [comment]
Thanks! I also opened an issue upstream at https://github.com/microsoft/vscode-python-tools-extension-template/issues/75 for us to look into incorporating a fix for this for everyone else as well.

**Comment by lsorber** [comment]
Is it possible to automatically detect if Ruff is available in the current Python environment and then use that version of Ruff instead of the version supplied with the extension?

**Comment by charliermarsh** [comment]
@lsorber - Yeah! Try these settings (with your path as-appropriate):

![Screen Shot 2022-11-24 at 9 48 57 AM](https://user-images.githubusercontent.com/1309177/203812266-05b25a04-6483-482c-b80e-48fe7bb1f48a.png)
