### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by tekumara** [charliermarsh/vscode-ruff#20]
```
Failed to handle notification "textDocument/didSave": text_document=TextDocumentIdentifier(uri='file:///Users/tekumara/code/snowflakeutils/config.py') text=None
Traceback (most recent call last):
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-arm64/bundled/libs/pygls/protocol.py", line 316, in _handle_notification
    self._execute_notification(handler, params)
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-arm64/bundled/libs/pygls/protocol.py", line 223, in _execute_notification
    handler(*params)
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-arm64/bundled/tool/server.py", line 83, in did_save
    diagnostics: list[lsp.Diagnostic] = _linting_helper(document)
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-arm64/bundled/tool/server.py", line 105, in _linting_helper
    return _parse_output_using_regex(result.stdout) if result.stdout else []
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.12-darwin-arm64/bundled/tool/server.py", line 134, in _parse_output_using_regex
    for check in json.loads(content):
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tekumara** [comment]
This was the earlier version, I've upgraded to 2022.0.13 and still get the error:

```
Failed to handle notification "textDocument/didSave": text_document=TextDocumentIdentifier(uri='file:///Users/tekumara/code/snowflakeutils/config.py') text=None
Traceback (most recent call last):
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.13-darwin-arm64/bundled/libs/pygls/protocol.py", line 316, in _handle_notification
    self._execute_notification(handler, params)
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.13-darwin-arm64/bundled/libs/pygls/protocol.py", line 223, in _execute_notification
    handler(*params)
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.13-darwin-arm64/bundled/tool/server.py", line 84, in did_save
    diagnostics: list[lsp.Diagnostic] = _linting_helper(document)
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.13-darwin-arm64/bundled/tool/server.py", line 106, in _linting_helper
    return _parse_output_using_regex(result.stdout) if result.stdout else []
  File "/Users/tekumara/.vscode/extensions/charliermarsh.ruff-2022.0.13-darwin-arm64/bundled/tool/server.py", line 135, in _parse_output_using_regex
    for check in json.loads(content):
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by charliermarsh** [comment]
Okay thanks. Could you post your `settings.json` (or the relevant parts for Ruff)?

**Comment by tekumara** [comment]
This is [my settings.json](https://github.com/tekumara/setup/blob/e8fd160a76c9b1a8244a694d629aef91bae2ddda/dotfiles/Library/Application%20Support/Code/User/settings.json) but I don't have any ruff-specific stuff there.

**Comment by tekumara** [comment]
OK so it happening because i have
```
fix = true
```

in _pyproject.toml_. If I comment this out, it works!

**Comment by tekumara** [comment]
OK so it's happening because i have
```
fix = true
```

in _pyproject.toml_. If I comment this out, it works!

**Comment by tekumara** [comment]
OK so it's happening because i have
```
fix = true
```

in _pyproject.toml_ under `[tool.ruff]`. If I comment this out, it works!

**Comment by charliermarsh** [comment]
Ohhh interesting. That _does_ makes sense. If you have `fix = true`, we output the fixed source code... which isn't JSON serializable.

**Comment by charliermarsh** [comment]
Maybe we should pass `--no-fix` within the plugin for now.

**Comment by charliermarsh** [comment]
Changed this in the most recent release.
