### ISSUE TITLE
vscode-ruff crash if using python 3.10+ without typing-extensions installed

### ISSUE THREAD

**Issue by kalvin807** [charliermarsh/vscode-ruff#48]
The extension crash with this trace `ModuleNotFoundError: No module named 'typing_extensions'` when I run this extension on a python 3.10 installed mac.

# Cause

This is the line I think is problematic
```py
    from typing_extensions import TypedDict
```
Fresh python does not come with typing_extensions so this import fails.

Look like `TypedDict` is in `typing` after python 3.8+, so I think we need to import from typing if the python version is 3.8+
Ref https://peps.python.org/pep-0589/

Edited: Quick idea to fix is to try to import everything from `typing`, only try typing_extensions if it fails.

# Stacktrace
```
Name: Ruff
Module: ruff
Python extension loading
Waiting for interpreter from python extension.
Python extension loaded
Server Command [RUN]: /Users/---/.pyenv/versions/3.10.1/bin/python /Users/---/.vscode/extensions/charliermarsh.ruff-2022.0.19-darwin-arm64/bundled/tool/server.py
Server Command [DEBUG]: /Users/---/.pyenv/versions/3.10.1/bin/python /Users/---/.vscode/extensions/charliermarsh.ruff-2022.0.19-darwin-arm64/bundled/tool/_debug_server.py
Traceback (most recent call last):
  File "/Users/---/.vscode/extensions/charliermarsh.ruff-2022.0.19-darwin-arm64/bundled/tool/server.py", line 14, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
[Info  - 1:20:30 PM] Connection to server got closed. Server will restart.
Traceback (most recent call last):
  File "/Users/---/.vscode/extensions/charliermarsh.ruff-2022.0.19-darwin-arm64/bundled/tool/server.py", line 14, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
[Info  - 1:20:30 PM] Connection to server got closed. Server will restart.
[Error - 1:20:30 PM] Connection to server is erroring. Shutting down server.
Traceback (most recent call last):
  File "/Users/---/.vscode/extensions/charliermarsh.ruff-2022.0.19-darwin-arm64/bundled/tool/server.py", line 14, in <module>
    from typing_extensions import TypedDict
ModuleNotFoundError: No module named 'typing_extensions'
```

Thanks for the work tho! It looks awesome. Please let me know if any more information you need, or if any things I can help with!

**Comment by charliermarsh** [comment]
Gah, sorry, let me take a look at this.

**Comment by charliermarsh** [comment]
Can you try again with `v2022.0.20`, which just went live?

**Comment by kalvin807** [comment]
it works. Thank you!
